# Generated by Django 5.1.4 on 2025-02-03 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='payment_amount',
        ),
    ]
